# Overlay Reset - Remove overlays from Plex media posters
# Run manually: docker compose -f /srv/overlay-reset/docker-compose.yml run --rm overlay-reset --items
# https://github.com/Kometa-Team/Overlay-Reset

services:
  overlay-reset:
    image: kometateam/overlay-reset:v1.0.4
    container_name: overlay-reset
    user: "3005:3005"
    env_file:
      - /srv/overlay-reset/.env
    network_mode: host
    volumes:
      - /srv/overlay-reset/config:/config:rw
      - /srv/kometa/config/assets:/assets:ro
      - /srv/kometa/config/overlays:/overlays:ro
    security_opt:
      - no-new-privileges:true
